### ISSUE TITLE
default language

### ISSUE THREAD

**Issue by slypire** [gupekmop/youtube#1]
How do I set different default language and different default keyboard, to en-US?

**Comment by gupekmop** [comment]
Search in `apps/magcore-app-youtube/3.0.13/js/release.js` code

![изображение](https://user-images.githubusercontent.com/74903658/104999824-16c06580-5a60-11eb-9fa3-06d10d148748.png)

Change default language and order

**Comment by slypire** [comment]
I tried like this:
![image](https://user-images.githubusercontent.com/51273686/105000845-2b383a00-5a2f-11eb-8a39-9d9cbbf4d987.png)

and i changed line 801:
![image](https://user-images.githubusercontent.com/51273686/105000927-49059f00-5a2f-11eb-979f-a23240f84898.png)


keyboard is now in english but on the right side it still says its on RU(but letters are english), and rest of the options like go back etc, they are all in russian..

**Comment by gupekmop** [comment]
change order in this strings too
from
`languagesCodeLocalized: ["\u0420\u0423", "EN", "\u0423\u041a\u0420", "DE", "AR"],`
`languagesLocalized: ["\u0420\u0443\u0441\u0441\u043a\u0438\u0439", "English", "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430", "Deutch", "Arabian"],`

to
`languagesCodeLocalized: ["EN", "\u0420\u0423", "\u0423\u041a\u0420", "DE", "AR"],`
`languagesLocalized: ["English", "\u0420\u0443\u0441\u0441\u043a\u0438\u0439", "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430", "Deutch", "Arabian"],`


Change language settings in `apps/magcore-app-youtube/3.0.13/youtube.php` for trending/search results

**Comment by slypire** [comment]
Changed it, now default is english and keyboard is in english, but when I try to exit the app using back button, its again on russian.

![image](https://user-images.githubusercontent.com/51273686/105005250-5a51aa00-5a35-11eb-9295-e993e3070250.png)

Everything else looks fine now, this seems to be only issue..

![image](https://user-images.githubusercontent.com/51273686/105005355-7fdeb380-5a35-11eb-98d4-ec402c168499.png)
![image](https://user-images.githubusercontent.com/51273686/105005432-9f75dc00-5a35-11eb-81b4-337046c26ec6.png)

**Comment by gupekmop** [comment]
Exit phrase

![изображение](https://user-images.githubusercontent.com/74903658/105005900-820e3580-5a68-11eb-8891-c7aa1336ad2d.png)

change to "Exit from app?" phrase from lang files

**Comment by slypire** [comment]
Does this looks good?
![image](https://user-images.githubusercontent.com/51273686/105006364-d8fb1700-5a36-11eb-87ac-770acde1ff8f.png)

**Comment by gupekmop** [comment]
yeah!

**Comment by slypire** [comment]
Thanks, that was it, now everything works just fine.
I hope you will continue to develop this version as it really means a lot for us non android users!
