### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by simkergey** [gupekmop/youtube#10]
Добрый день.
Возможно ли добавить опцию выбора качества видео?
На старых приставках маг250 видео с высоким качеством очень сильно тормозит.

**Comment by gupekmop** [comment]
Привет, да там максимально 720p идет, даже это не слишком высокое качество.
Могу сказать, что где поменять, чтобы стало 360p, но для всех, без права выбора.
Делать выбор не хочу, нет времени и желания.

**Comment by simkergey** [comment]
И на этом спасибо )))
Где поменять?

**Comment by gupekmop** [comment]
[/apps/magcore-app-youtube/3.0.13/js/release.js](https://github.com/gupekmop/youtube/blob/master/apps/magcore-app-youtube/3.0.13/js/release.js#L2670)

поменять строки 2670-2673

```
if (formats[i]["mimeType"].match(/^video\/(mp4|3gpp);/) && formats[i].hasOwnProperty("audioChannels") && formats[i].hasOwnProperty("width") && width < formats[i]["width"]) {
	id = i;
	width = formats[i]["width"];
}
```

на

```
if (formats[i]["mimeType"].match(/^video\/(mp4|3gpp);/) && formats[i].hasOwnProperty("audioChannels") && formats[i].hasOwnProperty("width") && width_short > formats[i]["width"]) {
	id = i;
	width_short = formats[i]["width"];
}
```

**Comment by simkergey** [comment]
Спасибо.

Сделал вот так:
>         var old_stb_model = ["MAG250", "MAG254", "MAG275", "MAG276"].indexOf(require(53).deviceModel()) !== -1;
>          for (var i = 0; i < length; i++) {
>            if ((formats[i].hasOwnProperty("approxDurationMs") && formats[i]["approxDurationMs"] < 60000) || (old_stb_model)) {

**Comment by simkergey** [comment]
Директор )))
Можно ли у плеера увеличить буфер?
При понижении качества часть роликов стало нормально показывать, но не все, некоторые тормозят.

**Comment by gupekmop** [comment]
видимо mag250 совсем днище, я на mag322 тестчу, на ней все норм 720p

**Comment by simkergey** [comment]
Согласен, что днище, у меня на 322 тоже все норм показывает, но хочется и на старых приставках запустить. Они хоть и старые, но хд тянут и видимо должны ютубовские ролики тоже тянуть.
