### ISSUE TITLE
Bad video quality

### ISSUE THREAD

**Issue by antiuser** [gupekmop/youtube#2]
Hi there! I found one issue, that some video with FHD quality showing in youtube stalker plugin with minimal quality (e.g. 360p).
So, for example [this](https://www.youtube.com/watch?v=ipAnwilMncI) video.
Plugin version 4.0.3 downloaded now

**Comment by gupekmop** [comment]
Hi, I know about this problem. This plugin playback video which included audiotrack (searching best quality with audio). FHD video usually without audiotrack (video/audio with different URL). I don't know how playback 2 streams at the same time. :(
