### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by antiuser** [gupekmop/youtube#4]
Hi!
Search not working on latest version. Just yellow stripe after search
UPD. Search working through API

**Comment by gupekmop** [comment]
Hi, are you sure, what you try on latest version? Fixed search 6 day ago

**Comment by antiuser** [comment]
> Hi, are you sure, what you try on latest version? Fixed search 6 day ago

Yes, im sure, downloaded latest version today
md5 681a7f08bb78aded9c2fd6f91e3f0737  4.0.3.zip

**Comment by gupekmop** [comment]
Hmmm, ZIP release include old files, check tomorrow.
Change manually 174 line ../[youtube.php](https://github.com/gupekmop/youtube/commit/69f6e43e6f3a0062a7c486c8a1b93a1a81f42971#diff-6c87d98434d59cadd58637714ef37394f50895ada5b662018ab11674d3f646e8)

**Comment by antiuser** [comment]
> Hmmm, ZIP release include old files, check tomorrow.
> Change manually 174 line ../[youtube.php](https://github.com/gupekmop/youtube/commit/69f6e43e6f3a0062a7c486c8a1b93a1a81f42971#diff-6c87d98434d59cadd58637714ef37394f50895ada5b662018ab11674d3f646e8)

Yes, this helped.
Thank you
