### ISSUE TITLE
Video playback issue

### ISSUE THREAD

**Issue by antiuser** [gupekmop/youtube#5]
It is believed that videos longer than one hour do not play with yellow stripe (video unavailable), but less than one hour can be played without problems

**Comment by gupekmop** [comment]
I'm on vacation until September. I do not have a device for checking. Maybe it will work earlier. Sorry

**Comment by antiuser** [comment]
I have idea, that is TVIP STB firmware bug, after update firmware all works as shoud. But check on another device
